apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-dhl
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ondrejsika-hello-dhl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2025-11-10_docker-kubernetes-dhl.git
    path: ./kubernetes/hello_dhl_openshift